/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'airplay.';

export const start = {
  key: `${prefix}start`,
  text: 'Start AirPlay',
} as const satisfies Text;

export const stop = {
  key: `${prefix}stop`,
  text: 'Stop AirPlay',
} as const satisfies Text;
