/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'buttons.';

export const play = {
  key: `${prefix}play`,
  text: 'Play',
} as const satisfies Text;

export const pause = {
  key: `${prefix}pause`,
  text: 'Pause',
} as const satisfies Text;

export const replay = {
  key: `${prefix}replay`,
  text: 'Replay',
} as const satisfies Text;

export const mute = {
  key: `${prefix}mute`,
  text: 'Mute',
} as const satisfies Text;

export const unmute = {
  key: `${prefix}unmute`,
  text: 'Unmute',
} as const satisfies Text;
