/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'captions.';

export const enable = {
  key: `${prefix}enable`,
  text: 'Enable captions',
} as const satisfies Text;

export const disable = {
  key: `${prefix}disable`,
  text: 'Disable captions',
} as const satisfies Text;
