/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'cast.';

export const start = {
  key: `${prefix}start`,
  text: 'Start casting',
} as const satisfies Text;

export const stop = {
  key: `${prefix}stop`,
  text: 'Stop casting',
} as const satisfies Text;

export const connecting = {
  key: `${prefix}connecting`,
  text: 'Connecting',
} as const satisfies Text;
