/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'fullscreen.';

export const enter = {
  key: `${prefix}enter`,
  text: 'Enter fullscreen',
} as const satisfies Text;

export const exit = {
  key: `${prefix}exit`,
  text: 'Exit fullscreen',
} as const satisfies Text;
