/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'live.';

export const playing = {
  key: `${prefix}playing`,
  text: 'Playing live',
} as const satisfies Text;

export const seekToEdge = {
  key: `${prefix}seekToEdge`,
  text: 'Seek to live edge',
} as const satisfies Text;

export const badge = {
  key: `${prefix}badge`,
  text: 'Live',
} as const satisfies Text;
