/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'menu.';

export const settings = {
  key: `${prefix}settings`,
  text: 'Settings',
} as const satisfies Text;

export const quality = {
  key: `${prefix}quality`,
  text: 'Quality',
} as const satisfies Text;

export const audio = {
  key: `${prefix}audio`,
  text: 'Audio',
} as const satisfies Text;

export const defaultText = {
  key: `${prefix}default`,
  text: 'Default',
} as const satisfies Text;

export const speed = {
  key: `${prefix}speed`,
  text: 'Speed',
} as const satisfies Text;

export const captions = {
  key: `${prefix}captions`,
  text: 'Captions',
} as const satisfies Text;

export const playbackRate = {
  key: `${prefix}playbackRate`,
  text: 'Playback rate',
} as const satisfies Text;

export const back = {
  key: `${prefix}back`,
  text: 'Back',
} as const satisfies Text;

export const off = {
  key: `${prefix}off`,
  text: 'Off',
} as const satisfies Text;

export const auto = {
  key: `${prefix}auto`,
  text: 'Auto',
} as const satisfies Text;

export const autoWithLabel = {
  key: `${prefix}autoWithLabel`,
  text: 'Auto ({label})',
} as const satisfies Text;

export const subtitles = {
  key: `${prefix}subtitles`,
  text: 'Subtitles',
} as const satisfies Text;
