/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'pip.';

export const enter = {
  key: `${prefix}enter`,
  text: 'Enter picture-in-picture',
} as const satisfies Text;

export const exit = {
  key: `${prefix}exit`,
  text: 'Exit picture-in-picture',
} as const satisfies Text;
