/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'seek.';

export const forward = {
  key: `${prefix}forward`,
  text: 'Seek forward {seconds} seconds',
} as const satisfies Text;

export const backward = {
  key: `${prefix}backward`,
  text: 'Seek backward {seconds} seconds',
} as const satisfies Text;
