/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'slider.';

export const seek = {
  key: `${prefix}seek`,
  text: 'Seek',
} as const satisfies Text;
