/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'status.';

export const captionsOn = {
  key: `${prefix}captionsOn`,
  text: 'Captions on',
} as const satisfies Text;

export const captionsOff = {
  key: `${prefix}captionsOff`,
  text: 'Captions off',
} as const satisfies Text;

export const paused = {
  key: `${prefix}paused`,
  text: 'Paused',
} as const satisfies Text;

export const playing = {
  key: `${prefix}playing`,
  text: 'Playing',
} as const satisfies Text;

export const fullscreen = {
  key: `${prefix}fullscreen`,
  text: 'Fullscreen',
} as const satisfies Text;

export const pip = {
  key: `${prefix}pip`,
  text: 'Picture in picture',
} as const satisfies Text;

export const exitPip = {
  key: `${prefix}exitPip`,
  text: 'Exit picture in picture',
} as const satisfies Text;
