/** Generated by packages/core/scripts/generate-i18n-locales.ts — do not edit. */
import type { Text } from '../text';

const prefix = 'time.';

export const current = {
  key: `${prefix}current`,
  text: 'Current time',
} as const satisfies Text;

export const duration = {
  key: `${prefix}duration`,
  text: 'Duration',
} as const satisfies Text;

export const remaining = {
  key: `${prefix}remaining`,
  text: 'Remaining',
} as const satisfies Text;

export const remainingSuffix = {
  key: `${prefix}remainingSuffix`,
  text: '{duration} remaining',
} as const satisfies Text;

export const showElapsed = {
  key: `${prefix}showElapsed`,
  text: '{duration}. Show elapsed time.',
} as const satisfies Text;

export const showDuration = {
  key: `${prefix}showDuration`,
  text: '{duration}. Show duration.',
} as const satisfies Text;

export const showRemaining = {
  key: `${prefix}showRemaining`,
  text: '{duration}. Show remaining time.',
} as const satisfies Text;

export const position = {
  key: `${prefix}position`,
  text: '{current} of {duration}',
} as const satisfies Text;
